### ISSUE TITLE
Classnames get prepended letter

### ISSUE THREAD

**Issue by killua-x** [jkphl/grunt-svg-sprite#68]
If I have classnames in my SVG to access the different layers, they get prepended with a letter. 
It depends which SVG it renders first one appends "a", second "b" and so on. 
I searched in the docs and Code to change it with a parameterr, could not find it. 
Anyone a clue how to set it? Or is it an error?

My Config:
```
 base: {
        expand: true,
        cwd: '<%= cfg.src %>/icons/base',
        src: ['**/*.svg'],
        dest: '<%= cfg.build %>/sprites',
        options: {
          dimension: {         // Set maximum dimensions 
            maxWidth: 32,
            maxHeight: 32
          },
          mode: {
            myMode: {
              mode: 'defs',
              dest: '',
              bust: false,
              inline: true,
              sprite: 'base.svg'
            }
          }
        }
      }
```

**Comment by jkphl** [comment]
Hi @killua-x,

the feature is called "class namespacing" and can be disabled via config (see the `namespaceClassnames` option [in the docs](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#sprite-svg-options)). There is no way to control the prefixes though, and there are a couple of issues around this (that's why you can disable it).

Cheers, Joschi

**Comment by killua-x** [comment]
Cheers. 
Thanks a lot. I totally oversaw that.  ^__^;

**Comment by jkphl** [comment]
You're welcome! :)
